---
- name: install ntp
  apt: pkg=ntp state=present

- name: drop ntp.conf for ntp server
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root mode=0644
  notify: "restart ntp"

- name: ensure ntp service
  service: name=ntp enabled=yes state=started
