---
- name: Ensure collectd packages
  apt: pkg={{item}} state=present
  tags: monitoring
  with_items:
    - collectd
    - collectd-core
    - collectd-utils

- name: Ensure collectd graphite writer plugin
  tags: monitoring
  apt: pkg=collectd-write-graphite state=present
  when: swift_collectd_server is defined and swift_collectd_server

- name: Create /etc/collectd/conf.d
  tags: monitoring
  file: path=/etc/collectd/conf.d owner=root mode=0700 state=directory

- name: Configure collectd
  tags: monitoring
  template: dest=/etc/collectd/collectd.conf src=collectd.conf.j2
  notify: restart collectd

- name: Configure base monitoring
  tags: monitoring
  template: dest=/etc/collectd/conf.d/base_monitoring.conf src=base_monitoring.conf.j2
  notify: restart collectd

- name: Count available swap files/partitions
  tags: monitoring
  shell: cat /proc/swaps | wc -l
  register: swaps

- name: Enable swap monitoring
  tags: monitoring
  template: dest=/etc/collectd/conf.d/swap.conf src=swap.conf.j2
  when: swaps.stdout|int > 1
  notify: restart collectd

- name: Disable swap monitoring (if swapless)
  tags: monitoring
  file: path=/etc/collectd/conf.d/swap.conf state=absent
  when: swaps.stdout|int == 1
  notify: restart collectd

- name: Configure collectd network plugin
  tags: monitoring
  template: dest=/etc/collectd/conf.d/network.conf src=network.conf.j2
  notify: restart collectd

- name: Configure collectd graphite plugin
  tags: monitoring
  template: dest=/etc/collectd/conf.d/graphite.conf src=graphite.conf.j2
  notify: restart collectd
  when: swift_collectd_server is defined and swift_collectd_server

- name: Configure collectd email plugin
  tags: monitoring
  template: dest=/etc/collectd/conf.d/email.conf src=email.conf.j2
  notify: restart collectd
  when: swift_collectd_email_notifications and swift_mail_recipients|count > 0
