# One time cluster setup items - should do dispersion population here, too
---
- name: one-time setup
  hosts: proxy
  tasks:
  - name: initialize swauth
    shell: swauth-prep -K {{swift_swauth_key}} && touch /etc/swift/swauth.prepped creates=/etc/swift/swauth.prepped
    when: swift_auth_type == 'swauth'
    notify: create swauth users

  handlers:
  - name: create swauth users
    shell: swauth-add-user -A http://127.0.0.1:8080/auth/ -K {{swift_swauth_key}} {{" -a " if item.admin else "" }} {{" -r " if item.reseller_admin else ""}} {{item.account}} {{item.user}} {{item.password}} | wc -l | grep '^0$'
    with_items: swift_users
