---
- name: ensure remove old statsd
  apt: pkg=statsd-c state=absent

- name: Ensure statsd packages
  apt: pkg=statsdpy state=present

- name: drop statsd conf
  template: dest=/etc/statsdpy.conf src=statsdpy.j2 mode=0644
  notify: restart statsdpy

- name: ensure statsd runs on startup
  service: name=statsdpy state=running enabled=yes
