---
- name: ensure proxy packages
  apt: pkg={{item}} state=present
  with_items:
    - memcached

- include: source-install.yml
  when: swift_deployment_method|lower == "source"

- include: package-install.yml
  when: swift_deployment_method|lower == "package"

- name: ensure memcache listening on swift-net
  lineinfile: 
    regexp: "^-l.*" 
    state: present 
    line: "-l {{lookup('hostip','cidr={{swift_nets[\"swift\"]}}')}}"
    dest: /etc/memcached.conf
  notify: restart memcached

- name: ensure memcache enabled
  service: name=memcached state=started enabled=yes

- name: ensure extra proxy packages
  apt: pkg={{item}} state=present
  with_items: swift_proxy_extra_packages

- name: drop a proper proxy-server.conf
  template: dest=/etc/swift/proxy-server.conf src=proxy-server.conf.j2 owner=swift group=swift mode=0644
  notify: restart proxy
