---
- name: ensure proxy packages
  apt: pkg={{item}} state=present
  with_items:
    - swift-proxy
    - memcached
    - zerocloud
    - zerovm-zmq
    - swift-middleware-liteauth

- name: ensure extra proxy packages
  apt: pkg={{item}} state=present
  with_items: swift_proxy_extra_packages

- name: drop a proper proxy-server.conf
  template: dest=/etc/swift/proxy-server.conf src=proxy-server.conf.j2 owner=swift group=swift mode=0644

#101365010295482388031
