---
- name: ensure proxy packages
  apt: pkg={{item}} state=present
  with_items:
    - memcached
    - zerovm-zmq

- include: source-install.yml
  when: swift_deployment_method|lower == "source"

- include: package-install.yml
  when: swift_deployment_method|lower == "package"

- name: ensure extra proxy packages
  apt: pkg={{item}} state=present
  with_items: swift_proxy_extra_packages

- name: drop a proper proxy-server.conf
  template: dest=/etc/swift/proxy-server.conf src=proxy-server.conf.j2 owner=swift group=swift mode=0644
