---
- include: zvm-source-install.yml
  when: zerovm_deployment_method|lower == "source"

- include: zvm-package-install.yml
  when: zerovm_deployment_method|lower == "package"

- include: source-install.yml
  when: swift_deployment_method|lower == "source"

- include: package-install.yml
  when: swift_deployment_method|lower == "package"

- name: Create zwift sysimage dir
  file: path={{zwift_sysimage_dir}} state=directory mode=0755

- name: Drop zerovm system images
  shell: if curl -skS {{item.url}} >{{zwift_sysimage_dir}}/{{item.name}}.tar.tmp; then mv {{zwift_sysimage_dir}}/{{item.name}}.tar.tmp {{zwift_sysimage_dir}}/{{item.name}}.tar; fi creates={{zwift_sysimage_dir}}/{{item.name}}.tar
  with_items: zwift_sysimages

- name: drop object-server conf
  template: dest=/etc/swift/object-server.conf src=object-server.conf.j2 owner=swift mode=0644
  notify: restart swift-object

- name: create swift-recon directories
  file: path={{item}} mode=0755 owner=swift group=swift state=directory
  with_items:
    - /var/cache/swift
    - /var/lock/swift

- name: start object-server
  service: name=swift-object enabled=yes state=started
