---
- name: Install packages
  apt: pkg="{{item}}"
  with_items:
   - zerovm-zmq

- include: source-install.yml
  when: swift_deployment_method|lower == "source"

- include: package-install.yml
  when: swift_deployment_method|lower == "package"

- name: drop object-server conf
  template: dest=/etc/swift/object-server.conf src=object-server.conf.j2 owner=swift mode=0644
  notify: restart swift-object

- name: start object-server
  service: name=swift-object enabled=yes state=started
