---
swift_ntp_client_nets: []
swift_ntp_servers:
      - "0.pool.ntp.org"
      - "1.pool.ntp.org"
      - "2.pool.ntp.org"
      - "3.pool.ntp.org"
swift_ntp_client_restrictions: "nomodify notrap"
swift_ntp_server_options: "iburst"