---
- name: install postfix packages
  apt: pkg={{item}} state=present
  with_items:
  - postfix

- name: drop postfix config
  template: src=main.cf.j2 dest=/etc/postfix/main.cf
  notify: restart postfix

- name: ensure postfix running
  service: name=postfix state=started enabled=yes

- name: ensure swiftops alias
  lineinfile:
    dest: /etc/aliases
    state: present
    regexp: "^swiftops:.*$"
    line: "swiftops: {{swift_swiftops_email}}"
  notify: rebuild aliases
