---
swift_proxy_extra_packages: []
swift_proxy_bind_address: 0.0.0.0

swift_statsd_host: "{{prefix}}-management"
swift_statsd_net: "{{swift_nets['monitoring']}}"
swift_statsd_ip: "{{lookup('hostip', 'host={{swift_statsd_host}} cidr={{swift_statsd_net}}')}}"
