---
- include: source-install.yml
  when: swift_deployment_method|lower == "source"

- include: package-install.yml
  when: swift_deployment_method|lower == "package"

- name: start container-server
  service: name=swift-container enabled=yes state=started

- name: drop container-server conf
  template: dest=/etc/swift/container-server.conf src=container-server.conf.j2 owner=swift mode=0644
  notify: restart swift-container
