---
# required for monitor-zbroker
- name: install python pre-reqs for monitor hosts
  apt: pkg={{item}} state=latest
  when: inventory_hostname == swift_collectd_host
  with_items:
    - python-yaml
    - python-requests
    - python-alerter

- name: install python pre-reqs for all hosts
  apt: pkg={{item}} state=latest
  with_items:
    - python-alerter

- name: create alerter log directory
  file: path={{swift_alert_log_path}} owner={{swift_oper_user}} mode=700 state=directory

- name: drop alerter config
  template: dest=/etc/alerter.conf src=alerter.conf.j2 owner=swiftops mode=0600

- name: Create collectd script directory
  file: path="{{swift_collectd_script_dir}}" owner=root mode=0755 state=directory

- name: add zbroker test conf
  template: dest=/etc/zbroker_test.conf src=zbroker_test.conf.j2 owner=swiftops mode=0600
  notify: restart collectd

- name: Drop monitoring scripts
  copy: dest="{{swift_collectd_script_dir}}/{{item}}" src={{item}} owner=root mode=0755
  with_items: swift_collectd_scripts

- name: Configure monitoring scripts
  template: dest=/etc/collectd/conf.d/{{swift_collectd_exec_conf}} src=exec.conf.j2 owner=root mode=644
  notify: restart collectd
