---
# FIXME(rp): need network lookup
- name: add dsh entry
  lineinfile:
    create: yes
    dest: /home/{{swift_oper_user}}/.dsh/group/{{dsh_group}}
    state: present
    insertafter: EOF
    line: "{{swift_oper_user}}@{{lookup('hostip', 'cidr={{swift_nets[\"management\"]}}')}}"
    owner: "{{swift_oper_user}}"
    mode: 0600
  delegate_to: "{{dsh_server}}"

# FIXME(rp): need network lookup
- name: add to known_hosts
  lineinfile:
    create: yes
    dest: /home/{{swift_oper_user}}/.ssh/known_hosts
    state: present
    insertafter: EOF
    line: "{{lookup('hostip', 'cidr={{swift_nets[\"management\"]}}')}} ssh-rsa {{ansible_ssh_host_key_rsa_public}}"
    owner: "{{swift_oper_user}}"
    mode: 0600
  delegate_to: "{{dsh_server}}"

- name: add pubkey to authorized_hosts
  lineinfile:
    create: yes
    dest: /home/{{swift_oper_user}}/.ssh/authorized_keys
    state: present
    insertafter: EOF
    line: "{{hostvars[dsh_server]['cluster_ssh_pubkey']['stdout']}}"
