---
- name: install rsyslog packages
  apt: pkg={{item}} state=present
  with_items:
    - rsyslog

- name: drop rsyslog swift config
  template: src=10-swift.conf.j2 dest=/etc/rsyslog.d/10-swift.conf owner=root mode=0644
  notify: restart rsyslog

- name: drop rsyslog zpipes config
  template: src=20-zbroker.conf.j2 dest=/etc/rsyslog.d/20-zbroker.conf owner=root mode=0644
  notify: restart rsyslog

- name: ensure rsyslog startup
  service: name=rsyslog state=started enabled=yes

- name: drop rsyslog logrotates
  template: src=logrotate-swift.j2 dest=/etc/logrotate.d/swift owner=root mode=0644
