---
- name: Ensure storage server packages
  apt: pkg={{item}} state=present
  with_items:
  - xfsprogs
  - parted
  - rsync
  - sqlite3

- name: Ensure common storage packages
  apt: pkg={{item}} state=present
  with_items: swift_storage_extra_packages

- name: Ensure udev rules
  template:
    src: "{{swift_hwtype}}.udev.rules.j2"
    dest: /etc/udev/rules.d/00-swift.rules
    owner: root
    group: root
    mode: 0644
  notify: kick udev

- name: partition devices
  shell: echo 'y' | parted /dev/{{item}} mklabel gpt mkpart xfs 1m 100%; mkfs.xfs -f -i size=512 -d su=64k,sw=1 /dev/{{item}}1 creates=/dev/{{item}}1
  when: swift_manage_disks and ansible_devices.{{item}}.partitions|length == 0
  with_items: swift_devices

- name: ensure /srv/node
  file: path=/srv/node owner=root group=root mode=0755
  when: swift_manage_disks

- name: ensure mountpoints
  file: path=/srv/node/{{item}}
  with_items: swift_devices
  when: swift_manage_disks

- name: ensure mount
  mount:
    name: /srv/node/{{item}}
    src: /dev/{{item}}1
    opts: defaults,noatime,nodiratime,nobarrier,logbufs=8
    fstype: xfs
    state: mounted
  with_items: swift_devices
  when: swift_manage_disks

- name: ensure mount permissions
  file: path=/srv/node/{{item}} owner=swift
  with_items: swift_devices
  when: swift_manage_disks

- name: drop a proper defaults/rsyncd
  template: dest=/etc/default/rsync src=rsync.default.j2 mode=0644
  notify: restart rsync

- name: drop a proper rsyncd.conf
  template: dest=/etc/rsyncd.conf src=rsyncd.conf.j2 mode=0644
  notify: restart rsync

- name: drop corruption check script
  copy: src=xfs_corruption_check.sh dest=/usr/local/bin/xfs_corruption_check.sh mode=0755 owner=root group=root

- name: drop xfs corruption check cron
  template: dest=/etc/cron.d/corruption-check src=corruption-check.j2 mode=0644 owner=root

- name: drop /srv swift ownership cron
  cron: name="srv-chmod" minute="*/5" job="find /srv/node -maxdepth 1 -fstype xfs -print0 | xargs -n10 -0 sudo chown swift"