---
swift_collectd_script_dir: "/usr/share/collectd-scripts"
swift_collectd_scripts:
  - monitor-dispersion
  - monitor-md5
  - monitor-quarantine
  - monitor-umount
swift_collectd_exec_conf: "collectd-management.conf"